import { Player } from './player.model';

export const PLAYERS: Player[] = [
  new Player("Osvaldo Alonso", "6 Midfielder", 31, "5'11", 155, "2016 (Seattle): In one of the most productive seasons of his career, Alonso matched a career high with three goals while setting a new personal best with four assists. He started each of his 32 matches, marking the fourth time in his eighth years with the Rave Green that he played in at least 30 league fixtures. His goals came against Real Salt Lake (March 12), LA Galaxy (September 25) and Vancouver Whitecaps FC (October 2). The Sounders FC original also recorded two assists in a 5-0 rout over FC Dallas (July 13). For his efforts, Alonso was voted Team MVP for the fifth time in nine seasons. The club’s all-time leader in minutes in both the regular season and postseason, Alonso started all six of the club’s matches in the MLS Cup Playoffs. The midfield terror led MLS with 85 tackles won and 272 duels won, while finishing first among field players with 275 recoveries.", 1),

  new Player("Clint Dempsey", "2 Forward ", 34, "6'1", 170, "2016 (Seattle): One of the most decorated players in American soccer history, Dempsey scored eight goals and added two assists in his 17 league matches in 2016. He also had a brace in the first leg of the Scotiabank CONCACAF Champions League Knockout Round against Club America (February 23). In addition to goals in home contests versus Montreal (April 2), San Jose (May 7) and FC Dallas (July 13), Dempsey had a pair of multi-goal games. At Orlando City, he became the first player in club history to record two hat tricks (August 7). In his final appearance, the forward bagged a brace against rival Portland (August 21). On August 26, Dempsey was diagnosed with an irregular heartbeat and sidelined from club and country competitions for the remainder of 2016. With the USMNT, Dempsey made 10 appearances and scored four goals in 2016.", 2),

  new Player("Brad Evans", "3 Defender/Midfielder", 32, "6'1", 170, "2016 (Seattle): One of two players remaining from the original 2009 squad, Evans appeared in 23 league matches, making 21 starts. He began the season on club’s backline, slotting in at central defender alongside Chad Marshall. By season’s end, Evans proved his versatility as a midfielder, as well. He scored the 24th goal of his MLS career in a 2-1 win at Vancouver Whitecaps FC with an 81st minute penalty-kick winner (October 2). One of the most efficient spot-takers in league history, Evans improved to 11/11 all-time in penalty-kick attempts across all competitions for Seattle. This reliability also came in clutch during the MLS Cup, when Evans led off for Seattle with a converted attempt from the spot.", 3)
];
